### ISSUE TITLE
App crashes after login with Samsung Tablet

### ISSUE THREAD

**Issue by tcarlyle** [SINTEF-SIT/emht-app#26]
The app seems to be working fine in the smartphones, but when using the Samsung Tablet the app crashes after the login. The error is pasted below and it seems to be related with the mapview fragment:

08-26 09:34:20.084  15115-15115/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: sintef.android.emht, PID: 15115
    java.lang.RuntimeException: Unable to start activity ComponentInfo{sintef.android.emht/sintef.android.emht.MapsActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:164)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5350)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at sintef.android.emht.MapsActivity.onCreate(MapsActivity.java:110)
            at android.app.Activity.performCreate(Activity.java:5428)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:164)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5350)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by iverasp** [comment]
Caused by incompatible version of Google Play Services on older devices. Fixed by checking for correct version on onResume and prompt user to update/install if needed.
